CREATE DATABASE userdb;
USE userdb;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

SELECT * FROM USERS;